version: '3.8'
services:
    node-express:
        container_name: vsnippet-sqli-login-20
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db-mysql
        volumes:
            - ./vsnippet:/var/www/html/
        ports:
            - 1337:1337
    db-mysql:
        container_name: vsnippet-db-mysql-sqli-login-20
        volumes:
            - ./config/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
        image: mysql@sha256:2247f6d47a59e5fa30a27ddc2e183a3e6b05bc045e3d12f8d429532647f61358
        environment:
            MYSQL_DATABASE: ywhvsnippet
            MYSQL_USER: vsnippet
            MYSQL_PASSWORD: vsnippet
            MYSQL_ROOT_PASSWORD: supervulnerableroot
        ports:
            - "1338:3306"
